name: Build and Test

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
      - master
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display GitVersion outputs
      run: echo Build
        
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Prep packages
      run: echo release