name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo Test
  code-quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code Quality
        run: echo Code Quality
  release:
    runs-on: ubuntu-latest
    needs: [build, test, code-quality]
    steps:
      - name: Release
        run: echo Release